name:                alpFinal
version:             0.1.0.0
github:              "githubuser/alpFinal"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/alpFinal#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- containers
- OpenGL
- GLUT
- bytestring
- text
- cereal
- attoparsec
- STL
- linear
- reactive-banana
- JuicyPixels
- vector
- xml
- split
- template-haskell

library:
  source-dirs: src

executables:
  alpFinal-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -dynamic
    dependencies:
    - alpFinal

tests:
  alpFinal-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -dynamic
    dependencies:
    - alpFinal
